import "./globals.css";
import { Lora } from "next/font/google";

const lora = Lora({
  weight: ["400"],
  subsets: ["latin"],
});

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import UserProvider from "./context/UserContext";
import CartProvider from "./context/Cart";

export const metadata = {
  title: "e-bay Clone",
  description: "This ebay-clone generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <ToastContainer />
        <UserProvider>
          <CartProvider>{children}</CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
